### ISSUE TITLE
getAllRows for Column Family with ByteOrder Partitioner does not return all rows

### ISSUE THREAD

**Issue by vgarud** [Netflix/astyanax#126]
My row key is a composite key and am using the AnnotatedCompositeSerializer.
I am using astayanax version 1.0.3

Here is my code snippet. It only returns 100 rows (as set in setRowLimit). 
Am I doing something wrong. Or is there another way to iterate through all rows for CF with ByteOrderPartitioner ?

// code begin
		ColumnFamilyQuery<WDKey, WDColumn> nq = keyspace.prepareQuery(WeatherColumnFamilies.CF_WEATHER_DATA);
		
		ArrayList<WDKey> list = new ArrayList<WDKey>();
		try
		{
			
			Rows<WDKey, WDColumn> rows = nq.getAllRows().setRowLimit(100)
                .withColumnRange(new RangeBuilder().setLimit(0).build())
                .execute().getResult();
			Iterator<Row<WDKey, WDColumn>> it = rows.iterator(); 
			while(it.hasNext()){
				Row<WDKey, WDColumn> r = it.next();
				WDKey key = r.getKey();
				System.out.println("Key - " + key.getCountry() + "-" + key.getZip());
			}
		}
		catch (ConnectionException e)
		{
			throw new RuntimeException("Can't get key list", e);
		}
// code end

**Comment by ckalantzis** [comment]
Byte order partitioning is not recommended in Cassandra:
http://docs.datastax.com/en/cassandra/1.2/cassandra/architecture/architecturePartitionerBOP_c.html

Although use cases may exist to use it, the number of them don't warrant the effort to fully support in Astyanax.

**Comment by carrino** [comment]
I think the amount of FUD around ordered keys vs hashed keys is quite unwarranted.  Once vnodes were added the only argument against them is "you need to think about how your data is laid out or you will get hotspots".  I think this is a weak argument because you really should think about how your data is laid out.  

Byte order is strictly better than hashed because you can always turn an ordered key into a hashed key by prepending the hash.   Saying this is always the correct choice for all users I think is a mistake.
