### ISSUE TITLE
Cannot build Context based on documenation

### ISSUE THREAD

**Issue by AtticusNotFinch** [Netflix/astyanax#230]
Many Bothans died to bring you this information:
suffered a series of exceptions sometimes at compile time sometimes at build time

they include

```
RUNTIME:
Caused by: java.lang.ClassNotFoundException: org.apache.cassandra.dht.RandomPartitioner

Caused by: java.lang.ClassNotFoundException: org.joda.time.DateTime

Caused by: java.lang.ClassNotFoundException: com.google.common.base.Supplier


java.lang.RuntimeException: Can't instantiate default partitioner com.netflix.astyanax.partitioner.BigInteger127Partitioner
Caused by: java.lang.NoClassDefFoundError: org/apache/cassandra/dht/RandomPartitioner

COMPILE:
cannot access org.apache.cassandra.thrift.Cassandra
class file for org.apache.cassandra.thrift.Cassandra not found
```

Addressing each of these boils down to adding the following dependencies:

``` xml

        <dependency>
            <groupId>org.apache.cassandra</groupId>
            <artifactId>cassandra-all</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>11.0.2</version>
        </dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.0</version>
        </dependency>

```

I hope this helps someone.  It seems that maven ought to import these libraries automatically.

**Comment by hanshika0292** [comment]
Having Similar problem:

Getting following error:
Information:Using javac 1.8.0_101 to compile java sources
Information:java: Errors occurred while compiling module <proj_name>
Information:Module <proj_name> was fully rebuilt due to project configuration/dependencies changes
Information:23/8/16 12:17 PM - Compilation completed with 1 error and 3 warnings in 2s 173ms
Warning:java: source value 1.5 is obsolete and will be removed in a future release
Warning:java: target value 1.5 is obsolete and will be removed in a future release
Warning:java: To suppress warnings about obsolete options, use -Xlint:-options.
<proj_name>/src/main/java/org/sample/cassandra/Application.java
Error:(54, 17) java: cannot access org.apache.cassandra.thrift.Cassandra
  class file for org.apache.cassandra.thrift.Cassandra not found


My pom file dependencies:

  <dependencies>
        <dependency>
            <groupId>com.netflix.astyanax</groupId>
            <artifactId>astyanax-core</artifactId>
            <version> 3.9.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.netflix.astyanax</groupId>
            <artifactId>astyanax-thrift</artifactId>
            <version> 3.9.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.netflix.astyanax</groupId>
            <artifactId>astyanax-cassandra</artifactId>
            <version>3.9.0</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
